# Generated by Django 5.0.14 on 2026-06-11 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('LEAVE', 'Leave'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=20)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_lat_in', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng_in', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lat_out', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng_out', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', '-check_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
